# see documentation, e.g.
# - https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata
# - https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
# - https://www.python.org/dev/peps/pep-0621/

[build-system]
requires = ["setuptools>=77.0.3", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
authors = [
    { name = "Huanni Zhang", email = "huanni.zhang@univie.ac.at" }
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = []
description = "A computational pipeline of small-molecule enantiomers binding conformation categorization"
keywords = ["small-molecule"," enantiomers"]
license = "MIT"
license-files = ["LICENSE"]
name = "enantiomer_binding_conformation"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.12"
version = "3.13.0"

[project.scripts]
enantiomer-pipeline = "enantiomer_pipeline.cli:main"

[tool.setuptools.packages.find]
where = ["src", "."]
include = ["enantiomer_binding_conformation*", "enantiomer_pipeline*"]

[dependency-groups]
dev = [
    "build",  # build is not only used in publishing (below), but also in the template's test suite
    "bump-my-version",
    "ruff",
    "tox",
    "myst_parser",
    
]
publishing = [
    "build",
    "twine",
    "wheel",
]

[project.urls]
Repository = "https://github.com/Huanni05/enantiomer_binding_conformation"
Issues = "https://github.com/Huanni05/enantiomer_binding_conformation/issues"





[tool.tox]
requires = ["tox>=4.22"]
env_list = [ "py312", "py313", "py314" ]
skip_missing_interpreters = true


[tool.ruff]
line-length = 79
output-format = "concise"

[tool.ruff.lint]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Enable Pyflakes `E` and `F` codes by default.
select = ["ALL"]
ignore = [
    "ANN204", # Missing return type annotation for special (dunder) method
    "FBT",    # Using boolean function arguments
    "TD",     # TODOs
    "FIX001", # Resolve FIXMEs
    "FIX002", # Resolve TODOs
    "B028",   # No explicit `stacklevel` keyword argument found in warning
    "COM812", # Trailing commas are taken care of by `ruff format`
    # No docstrings required in the following cases
    "D100", # Missing module docstring
    "D104", # Missing public package docstring
    "D105", # Missing docstring in magic method
    "D107", # Missing docstring in `__init__`
]
pydocstyle.convention = "google"

[tool.ruff.lint.per-file-ignores]
# Tests can ignore a few extra rules
"tests/**.py" = [
    "ANN201", # Missing return type annotation for public function
    "PT011",  # Missing `match` parameter in `pytest.raises()`
    "S101",   # Use of assert is detected
]

[tool.ruff.lint.isort]
known-first-party = ["enantiomer_binding_conformation"]
force-single-line = true
no-lines-before = ["future","standard-library","third-party","first-party","local-folder"]



[tool.bumpversion]
current_version = "3.13.0"

[[tool.bumpversion.files]]
filename = "src/enantiomer_binding_conformation/__init__.py"

[[tool.bumpversion.files]]
filename = "pyproject.toml"




